### ISSUE TITLE
Possible File Structure bug in 1.6-192-dev?

### ISSUE THREAD

**Issue by CanOfBees** [rhdunn/xquery-intellij-plugin#132]
I'm experiencing an odd problem witn 1.6-192-dev: the File Structure popup (and corresponding toolbar view) don't work, but only for XSL files. In the Structure toolbar view, it results in a blank window; when using the File Structure popup (ctrl+F12), it shows a "Structure is empty" message. 

The only thing that comes up in the `idea.log` is the following error message. Unfortunately, I can't seem to reproduce this in a Linux environment, but please let me know if there's anything other information I can provide. 

Thank you for your time.

```
2019-09-03 09:31:48,805 [315104730]  ERROR - ij.ide.IdeEventQueue.typeahead - Typeahead timeout is exceeded: 10088 
java.lang.RuntimeException: Typeahead timeout is exceeded: 10088
	at com.intellij.ide.IdeEventQueue.lambda$isTypeaheadTimeoutExceeded$18(IdeEventQueue.java:1167)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:817)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:405)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:404)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2019-09-03 09:31:48,806 [315104731]  ERROR - ij.ide.IdeEventQueue.typeahead - IntelliJ IDEA 2019.2.1  Build #IU-192.6262.58 
2019-09-03 09:31:48,807 [315104732]  ERROR - ij.ide.IdeEventQueue.typeahead - JDK: 1.8.0_212; VM: OpenJDK 64-Bit Server VM; Vendor: Oracle Corporation 
2019-09-03 09:31:48,807 [315104732]  ERROR - ij.ide.IdeEventQueue.typeahead - OS: FreeBSD 
2019-09-03 09:31:48,807 [315104732]  ERROR - ij.ide.IdeEventQueue.typeahead - Last Action: FileStructurePopup 
```

**Comment by rhdunn** [comment]
That's strange.The file structure view for XSL documents is provided by the IntelliJ XML support. As such, it should not be affected by the IntelliJ plugin.
