### ISSUE TITLE
Run Configuration error: Query Processor selection doesn't save

### ISSUE THREAD

**Issue by CanOfBees** [rhdunn/xquery-intellij-plugin#133]
Hi Reece - 

I'm seeing a couple of strange errors with Run Configuration, only on a Linux system. 

The first error: essentially, the Query Processor drop-down selection does not "stick" after selection; i.e. if I select BaseX 9.2.4, click 'Apply' then 'Close', re-opening the Edit Configuration dialog shows that there isn't a processor selected (see screen shots below). This results in the IDE throwing an `Error running 'test': Unknown error` and the attached error from the log.

Edit: this is happening on a recent build of the plugin: commit 2196dbc8.

I'll post a second issue for the other error.

[1] screen shots:
![run-config-select-apply](https://user-images.githubusercontent.com/2052902/67696402-33650f00-f97d-11e9-9d8d-f3122bf257e3.png)

![run-config-select-reopen](https://user-images.githubusercontent.com/2052902/67696414-395af000-f97d-11e9-9eb1-54e27abdb5dc.png)

[2] Trace in idea.log:
```
2019-10-28 11:30:36,608 [ 108440]   WARN - xecution.runners.ExecutionUtil - Execution error without description
kotlin.KotlinNullPointerException
    at uk.co.reecedunn.intellij.plugin.intellij.execution.configurations.QueryProcessorRunState.startProcess(QueryProcessorRunState.kt:50)
    at uk.co.reecedunn.intellij.plugin.intellij.execution.configurations.QueryProcessorRunState.execute(QueryProcessorRunState.kt:39)
    at com.intellij.execution.runners.DefaultRunProgramRunner.execute(DefaultRunProgramRunner.kt:42)
    at com.intellij.execution.runners.AsyncProgramRunner$execute$$inlined$runProfileStarter$1.executeAsync(GenericProgramRunner.kt:56)
    at com.intellij.execution.runners.GenericProgramRunnerKt$startRunProfile$$inlined$runProfileStarter$1.executeAsync(GenericProgramRunner.kt:56)
    at com.intellij.execution.impl.ExecutionManagerKtImpl$startRunProfile$startRunnable$1.run(ExecutionManagerKtImpl.kt:63)
    at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:82)
    at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:106)
    at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:115)
    at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
    at com.intellij.execution.impl.ExecutionManagerKtImpl$startRunProfile$2.run(ExecutionManagerKtImpl.kt:116)
    at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:278)
    at com.intellij.execution.impl.ExecutionManagerKtImpl.startRunProfile(ExecutionManagerKtImpl.kt:116)
    at com.intellij.execution.runners.GenericProgramRunnerKt.startRunProfile(GenericProgramRunner.kt:50)
    at com.intellij.execution.runners.AsyncProgramRunner.execute(GenericProgramRunner.kt:38)
    at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:46)
    at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:35)
    at com.intellij.execution.ProgramRunnerUtil.executeConfigurationAsync(ProgramRunnerUtil.java:92)
    at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:40)
    at com.intellij.execution.impl.ExecutionManagerImpl.restart(ExecutionManagerImpl.java:94)
    at com.intellij.execution.impl.ExecutionManagerImpl.access$300(ExecutionManagerImpl.java:45)
    at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:470)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:231)
    at com.intellij.util.Alarm$Request.runSafely(Alarm.java:368)
    at com.intellij.util.Alarm$Request.run(Alarm.java:355)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:224)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:824)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:773)
    at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:412)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by rhdunn** [comment]
Thanks for the report. I know what the problem is with this and can reproduce it. I'm investigating a solution.
