### ISSUE TITLE
Run Configuration error: Processor validation hangs

### ISSUE THREAD

**Issue by CanOfBees** [rhdunn/xquery-intellij-plugin#134]
After running into the odd behavior in #133, I thought trying to run a BaseX server instance might alleviate the problem, but unfortunately the `validating the query processor instance` never completes[1]. This results in the following error from idea.log[2].

Note I've tried with database server and the BaseX HTTP instance and both fail to validate. This particular problem is reproducible on both of the systems I have at hand.

This occurs with a very recent build of the plugin: 1.6-192-dev, from commit 2196dbc8.

Hope you're well. As usual, thanks for all of your work with the plugin.
Best,
Bridger

[1] screen shot
![run-config-validate-timeout](https://user-images.githubusercontent.com/2052902/67700029-8f329680-f983-11e9-87da-b97e686e76f6.png)

[2] error from idea.log:
```
2019-10-28 12:55:50,967 [5222799]  ERROR - llij.ide.plugins.PluginManager - com.intellij.credentialStore.CredentialAttributes.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Class;ZILkotlin/jvm/internal/DefaultConstructorMarker;)V                                                                                                                                                            
java.lang.NoSuchMethodError: com.intellij.credentialStore.CredentialAttributes.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Class;ZILkotlin/jvm/internal/DefaultConstructorMarker;)V       
    at uk.co.reecedunn.intellij.plugin.processor.query.ConnectionSettings.setPassword(ConnectionSettings.kt:38)                                                                                     
    at uk.co.reecedunn.intellij.plugin.intellij.settings.QueryProcessorSettingsDialogUI.apply(QueryProcessorSettingsDialog.kt:235)                                                                  
    at uk.co.reecedunn.intellij.plugin.intellij.settings.QueryProcessorSettingsDialogUI.apply(QueryProcessorSettingsDialog.kt:71)                                                                   
    at uk.co.reecedunn.intellij.plugin.intellij.settings.QueryProcessorSettingsDialog.validate(QueryProcessorSettingsDialog.kt:46)                                                                  
    at uk.co.reecedunn.intellij.plugin.core.ui.Dialog$run$1.run(Dialog.kt:40)                                                                                                                       
    at com.intellij.openapi.ui.DialogBuilder$MyDialogWrapper.doOKAction(DialogBuilder.java:420)                                                                                                     
    at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1861)                                                                                                             
    at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1821)
```

**Comment by rhdunn** [comment]
I don't see this error with the latest plugin version and IntelliJ version IC-192.5728.98.

Can you still reproduce this issue? What version and variant of IntelliJ are you using?

**Comment by CanOfBees** [comment]
Many apologies for the delayed response. 

Good news: I'm unable to recreate this bug on any of my machines (I'm using the latest plugin release (1.5.2-192) and IDEA IU-192.7142.36). Thanks for your help -- plugin v1.5.2-192 is fantastic!

I'm closing this issue.
