### ISSUE TITLE
can’t declare a new processor instance with BaseX

### ISSUE THREAD

**Issue by emchateau** [rhdunn/xquery-intellij-plugin#136]
I‘m trying to create a new processor instance with BaseX and after clicking OK, I’ve got the msg 

>validating the query processor instance

And nothing happen.

I‘m running the last BaseX version on a MacOS 10.13.6 with Webstorm 2020.1

Please find the log
>kotlin.TypeCastException: null cannot be cast to non-null type uk.co.reecedunn.intellij.plugin.xdm.types.XsDurationValue
	at uk.co.reecedunn.intellij.plugin.basex.query.session.BaseXRunnableQuery$run$1.invoke(BaseXRunnableQuery.kt:74)
	at uk.co.reecedunn.intellij.plugin.basex.query.session.BaseXRunnableQuery$run$1.invoke(BaseXRunnableQuery.kt:30)
	at uk.co.reecedunn.intellij.plugin.basex.query.session.BaseXQueryErrorKt.check(BaseXQueryError.kt:32)
	at uk.co.reecedunn.intellij.plugin.basex.query.session.BaseXRunnableQuery.run(BaseXRunnableQuery.kt:64)
	at uk.co.reecedunn.intellij.plugin.basex.query.session.BaseXQueryProcessor.getVersion(BaseXQueryProcessor.kt:36)
	at uk.co.reecedunn.intellij.plugin.intellij.settings.QueryProcessorSettingsDialog$validate$1.invoke(QueryProcessorSettingsDialog.kt:51)
	at uk.co.reecedunn.intellij.plugin.intellij.settings.QueryProcessorSettingsDialog$validate$1.invoke(QueryProcessorSettingsDialog.kt:37)
	at uk.co.reecedunn.intellij.plugin.core.async.ApplicationKt$sam$java_lang_Runnable$0.run(Application.kt)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by rhdunn** [comment]
Thanks for the report. I've identified the cause of the issue, and am working on a solution.

**Comment by rhdunn** [comment]
This fix is now available as part of the 1.6.2 release.

**Comment by emchateau** [comment]
Thanks a lot, I’ve just test it and it works fine !
