### ISSUE TITLE
Error validating 'New Query Processor Instance' 

### ISSUE THREAD

**Issue by CanOfBees** [rhdunn/xquery-intellij-plugin#137]
Hi Reece - 

I'm running into a little error with IDEA 2020.1.1  Build #IU-201.7223.91 and v1.6.2-201 of the plugin.

Attempting to update/add a new Query Processor Instance brings up the 'Validating the query processor instance...' message and then stops. The following error is returned in the log (below).

Let me know if there's any additional information I can provide.
Thank you!

```
2020-05-15 21:13:55,525 [122413198]  ERROR - pplication.impl.LaterInvocator - List is empty. 
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:196)
	at uk.co.reecedunn.intellij.plugin.basex.query.session.BaseXQueryProcessor.getVersion(BaseXQueryProcessor.kt:36)
	at uk.co.reecedunn.intellij.plugin.intellij.settings.QueryProcessorSettingsDialog$validate$1.invoke(QueryProcessorSettingsDialog.kt:51)
	at uk.co.reecedunn.intellij.plugin.intellij.settings.QueryProcessorSettingsDialog$validate$1.invoke(QueryProcessorSettingsDialog.kt:37)
	at uk.co.reecedunn.intellij.plugin.core.async.ApplicationKt$sam$java_lang_Runnable$0.run(Application.kt)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-05-15 21:13:55,526 [122413199]  ERROR - pplication.impl.LaterInvocator - IntelliJ IDEA 2020.1.1  Build #IU-201.7223.91 
2020-05-15 21:13:55,527 [122413200]  ERROR - pplication.impl.LaterInvocator - JDK: 11.0.5-internal; VM: OpenJDK 64-Bit Server VM; Vendor: Void 
2020-05-15 21:13:55,527 [122413200]  ERROR - pplication.impl.LaterInvocator - OS: Linux 
```

**Comment by rhdunn** [comment]
What version of BaseX are you using?

What does `db:system()/generalinformation/version/string()` display?

Note: this error was likely introduced when I added support for BaseX running in languages other than English.

**Comment by CanOfBees** [comment]
I rolled back IDEA to v2019.3.5 to work around this and I'm not experiencing the bug immediately, but:

BaseX version = 9.3.3 and 9.4 beta. 
Currently `db:system()/generalinformation/version/string()` returns `9.4. beta`.

Thanks for your help -- I'm happy to recheck with different versions of IDEA if that would be helpful.

**Comment by rhdunn** [comment]
Thanks. The issue was with the `9.4 beta` string -- I'm now using a regex to detect the version in order to support BaseX in other languages. That regex was only detecting versions like `n.n` and `n.n.n` (where `n` is a number), so I've extended it to support the " beta" text at the end.

This fix will be available in the next release (or you can build the project now if you want a preview :)).
